homeassistant:
  # Name of the location where Home Assistant is running
  name: Kroken
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HOME_LAT
  longitude: !secret HOME_LON
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  
  customize: !include customize.yaml
  
  auth_providers:
   - type: homeassistant
   # Uncomment next line if you want to enable legacy API password support
   #- type: legacy_api_password

# Enable the auth component
auth:


frontend:
  themes: !include themes.yaml

cloud:
  alexa:
    filter:
      include_domains:
        - light
        - switch
        - lock
        - script
        - group

config:

http:
  api_password: !secret HTTP_PASSWORD
  base_url: !secret HTTP_BASE_URL
  server_port: !secret HTTP_SERVER_PORT
  ip_ban_enabled: True
  login_attempts_threshold: 10
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24

updater:
discovery:
conversation:
sun:
ios:
ffmpeg:
    ffmpeg_bin: /usr/bin/ffmpeg

logger:
  default: warn
#  logs:
#    homeassistant.components.camera: debug
#    custom_components.camera.onvif: debug

# Enables support for tracking state changes over time.
recorder: !include recorder.yaml
logbook: !include logbook.yaml      
history: !include history.yaml

#influxdb:
     
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret ZWAVE_NETWORK_KEY

climate:
  - platform: zwave
  - platform: sensibo
    api_key: !secret SENSIBO_API_KEY

automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list sensor
group: !include_dir_merge_named group
media_player: !include media_player.yaml
#input_boolean: !include_dir_merge_list input_boolean
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
camera: !include camera.yaml
notify: !include notify.yaml
alert: !include alerts.yaml
zone: !include zone.yaml
#cover: !include cover.yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

#panel_custom:
#  - name: floorplan
#    sidebar_title: Planløsning
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.177
    token: !secret XIAOMI_TOKEN

verisure:
  username: !secret VERISURE_USERNAME
  password: !secret VERISURE_PASSWORD
  alarm: 0
  hygrometers: 0
  smartplugs: 0
  thermometers: 0
  locks: 1
  mouse: 0
  code_digits: !secret VERISURE_CODE_DIGITS

netatmo:
  api_key: !secret NETATMO_API_KEY
  secret_key: !secret NETATMO_SECRET_KEY
  username: !secret NETATMO_USERNAME
  password: !secret NETATMO_PASSWORD

tellduslive:
  host: "192.168.1.32"
  update_interval: 5

device_tracker:
  - platform: unifi
    host: !secret UNIFI_HOST
    username: !secret UNIFI_USERNAME
    password: !secret UNIFI_PASSWORD
    verify_ssl: false
    consider_home: 180
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    mqtt_topic: "owntracks/#"
  - platform: bluetooth_tracker

mqtt:
    broker: m21.cloudmqtt.com
    port: !secret CLOUD_MQTT_PORT
    username: !secret CLOUD_MQTT_USERNAME
    password: !secret CLOUD_MQTT_PASSWORD
    
weather:
  - platform: yweather
    
#homekit:
#  pincode: !secret HOMEKIT_PIN
    
# Text to speech
tts:
  platform: google