- name: HTML5
  platform: html5
  gcm_api_key: 'AAAAl8fydzU:APA91bFRZUZc6PdlZ96ZJ67-BoIxciY3R04US2H6crLtEXiOPRNXyopLD4kG7skhhOU_efMeTwUOyHLDXQMwX_3DyQGnD7YogYuId1zB0OSFFPU0RBbGYFbIQc6vkT9fUedImYHQgEIA'
  gcm_sender_id: '651894617909'

#-------------------------------------------
#  Default Notifier (all things use this)
#-------------------------------------------
- name: primary_contact
  platform: group
  services:
    - service: ios

#-------------------------------------------
#  Emergency Notices via SMS
#-------------------------------------------
- name: emergency_contact
  platform: group
  services:
    - service: sms
      data:
        target:
          - !secret VERONICA_MOBIL_NUM
          - !secret ROBERT_MOBIL_NUM

#-------------------------------------------
#  Clickatell SMS Notices Robert
#-------------------------------------------
- platform: clickatell
  name: sms_robert
  api_key: !secret CLICKATELL_API_KEY
  recipient: !secret ROBERT_MOBIL_NUM
  
- platform: clickatell
  name: sms_veronica
  api_key: !secret CLICKATELL_API_KEY
  recipient: !secret VERONICA_MOBIL_NUM

#-------------------------------------------
#  iOS Push (just Robert)
#-------------------------------------------
- name: ios_robert
  platform: group
  services:
    - service: ios_robert_iphone7
#    - service: ios_robertiphone7
    
- name: ios_veronica
  platform: group
  services:
#    - service: ios_veronica
    - service: ios_veronicaiphone6s

#-------------------------------------------
#  iOS Push (both)
#-------------------------------------------
- name: ios_both
  platform: group
  services:
    - service: ios_robert_iphone7
#    - service: ios_robertiphone7
#    - service: ios_veronica
    - service: ios_veronicaiphone6s