security_smoke_alarm_status:
  name: Røykvarslere
  entities:
  - sensor.smokealarm_livingroom
  - sensor.smokealarm_hallway
  - sensor.smokealarm_gl_bedroom
  - sensor.smokealarm_gl_livingroom
  view: false
  
awsome_people:
  name: Personer
  entities:
  - device_tracker.robert
  - device_tracker.robertiphone7
  - device_tracker.veronica
  view: false
  
door_windows:
  name: Dør og vinduer
  entities:
  - lock.ytterdr
  - sensor.magnet_dor_ytterdor
  - sensor.magnet_vaskeromdor
#  - garagedoor1_status
  view: false
  
motion:
  name: Bevegelse
  entities:
  - sensor.motion_entry
  - sensor.motion_livingroom
  control : hidden
  view: false