# LEAF: Charge-reminder
- alias: 'Carwings reminder'
  trigger:
  - platform: time
    at: "21:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.robandre_plug_status
        state: 'False'
      - condition: numeric_state
        entity_id: sensor.robandre_charge
        below: '50'
  action:
  - service: notify.ios_robert
    data:
        message: "Det er {{ states.sensor.robandre_charge.state }}% batteri på LEAF-en. Kanskje du vil lade den til i morgen?"
        title: "Nissan Leaf: Ladevarsling"