- alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: frontend.set_theme
    data:
        name: midnight
        
        
- alias: 'Set home status at startup'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.automation_away_auto
  - service: input_boolean.turn_on
    entity_id: input_boolean.automation_good_morning_auto
  - service: input_boolean.turn_on
    entity_id: input_boolean.automation_intruder_alert
    
    
- alias: 'Notification on restart'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.ios_robert
    data:
        message: "Home Assistant has been restarted"
        title: "Restart"
        
- alias: Log Level
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"