#Away
- alias: 'Borte'
  trigger:
    entity_id: input_boolean.away
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: notify.notify
    data:
        message: "Ytterdør låses og lys slås av om 60 sekunder"
        title: "Hadebra"
  - delay: 00:01:00
  - service: homeassistant.turn_off
    entity_id: group.lights
  - service: lock.lock
    data:
      code: '445566'
      entity_id: lock.ytterdr
  - service: input_boolean.turn_off
    entity_id: input_boolean.home
  - condition: and
    conditions:
        - condition: numeric_state
          entity_id: 'sensor.ute_temperature'
          below: '10'
  - service: climate.set_operation_mode
    data:
        entity_id: climate.stue
        operation_mode: 'Heat'
  - service: climate.set_temperature
    data:
        entity_id: climate.stue
        temperature: 18
  - condition: or
    conditions:
        - condition: numeric_state
          entity_id: 'sensor.ute_temperature'
          above: '10'
  - service: climate.set_operation_mode
    data:
        entity_id: climate.stue
        operation_mode: 'Off'
  - service: input_boolean.turn_off
    entity_id: input_boolean.home
  - service: input_boolean.turn_off
    entity_id: input_boolean.vacation
  - service: input_boolean.turn_off
    entity_id: input_boolean.go_to_sleep
    
    
# Away auto
- alias: 'Away Auto'
  trigger:
    entity_id: device_tracker.robertiphone7, device_tracker.veronica
    platform: state
    to: 'away'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.away
    

#Home
- alias: 'Hjemme'
  trigger:
    entity_id: input_boolean.home
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.away
  - service: input_boolean.turn_off
    entity_id: input_boolean.vacation
  - service: input_boolean.turn_off
    entity_id: input_boolean.go_to_sleep
#  - condition: and
#    conditions:
#        - condition: numeric_state
#          entity_id: 'sensor.ute_temperature'
#          below: '15'
#  - service: climate.set_operation_mode
#    data:
#        entity_id: climate.stue
#        operation_mode: 'Heat'
#  - service: climate.set_temperature
#    data:
#        entity_id: climate.stue
#        temperature: 23



# Home Auto
- alias: 'Hjemme Auto'
  trigger:
  - platform: state
    entity_id: device_tracker.robertiphone7
    from: 'away'
    to: 'home'
  - platform: state
    entity_id: device_tracker.veronica
    from: 'away'
    to: 'home'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home


    
#Good night
- alias: 'Natta'
  trigger:
    entity_id: input_boolean.go_to_sleep
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: notify.notify
    data:
        message: "Ytterdør låses. Lys slås av om 60 sekunder"
        title: "God natt"
  - service: lock.lock
    data:
      code: '445566'
      entity_id: lock.ytterdr
  - delay: 00:01:00
  - service: homeassistant.turn_off
    entity_id: group.lights
  - service: input_boolean.turn_on
    entity_id: input_boolean.home
  - service: input_boolean.turn_off
    entity_id: input_boolean.vacation
  - service: input_boolean.turn_off
    entity_id: input_boolean.away
  - service: switch.turn_on
    entity_id: switch.kjkken_lys_vindu
  - service: switch.turn_on
    entity_id: switch.gang_lyst_kommode_switch
#  - service: climate.set_temperature
#    data:
#        entity_id: climate.stue
#        temperature: 18

        
        
#Good morning auto
- alias: 'Good morning auto'
  trigger:
    entity_id: switch.bevegelse_stue
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: 'input_boolean.go_to_sleep'
      state: 'on'
    - condition: time
      after: '06:00:00'
      before: '10:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.go_to_sleep
      
      
      
#Good morning
- alias: 'Good morning'
  trigger:
    entity_id: input_boolean.go_to_sleep
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: notify.notify
    data:
        message: "Ytterdør låses opp. Lys slås på om det er mørkt."
        title: "God morgen"
  - service: lock.unlock
    data:
      code: '445566'
      entity_id: lock.ytterdr
  - condition: and
    conditions:
        - condition: template
          value_template: '{{ states.sun.sun.attributes.elevation < 20 }}'
  - service: switch.turn_on
    entity_id: switch.lys_pc_robert 
  - service: climate.set_temperature
    data:
        entity_id: climate.stue
        temperature: 24
      

#Vacation
- alias: 'Ferie'
  trigger:
    entity_id: input_boolean.vacation
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: notify.notify
    data:
        message: "Ytterdør låses og lys slås av om 60 sekunder"
        title: "Ha en god ferie"
  - delay: 00:01:00
  - service: homeassistant.turn_off
    entity_id: group.lights
  - service: lock.lock
    data:
      code: '445566'
      entity_id: lock.ytterdr
  - service: input_boolean.turn_off
    entity_id: input_boolean.home
  - service: input_boolean.turn_off
    entity_id: input_boolean.go_to_sleep
  - service: input_boolean.turn_on
    entity_id: input_boolean.away    
  - condition: and
    conditions:
        - condition: numeric_state
          entity_id: 'sensor.ute_temperature'
          below: '10'
  - service: climate.set_operation_mode
    data:
        entity_id: climate.stue
        operation_mode: 'Heat'
  - service: climate.set_temperature
    data:
        entity_id: climate.stue
        temperature: 16
  - condition: or
    conditions:
        - condition: numeric_state
          entity_id: 'sensor.ute_temperature'
          above: '10'
  - service: climate.set_operation_mode
    data:
        entity_id: climate.stue
        operation_mode: 'Off'