#Intruder alert
- alias: 'IntruderAlert'
  trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_motion_1_sensor
    to: 'on'
  - platform: state
    entity_id: sensor.motion_livingroom_alarm_level
    to: '255'
  condition:
  - condition: state
    entity_id: input_boolean.home
    state: 'off'
  action:
  - service: notify.notify
    data:
        message: Noen er i huset
        title: "Innbruddsalarm!"
        
        
# Magnet test
- alias: 'MagnetTest'
  trigger:
  - platform: state
    entity_id: switch.magnet_ytterdr
    from: 'off'
    to: 'on'
  action:
  - service: notify.ios_robertiphone7
    data:
        message: "Magnet triggered"
        title: "Ytterdør åpnet"
