# Motion Lights laundry-room
# Turn on ceiling lights when motion in laundry-room
- alias: 'Bevegelse Lys Vaskerom På'
  trigger:
    entity_id: switch.bevegelse_gang
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.vaskerom_bod_lys_switch
  - service: switch.turn_on
    entity_id: switch.vaskerom_bod_lys_switch_2

# Turn off ceiling lights when motion in laundry-room stops
- alias: 'Bevegelse Lys Vaskerom Av'
  trigger:
    entity_id: switch.bevegelse_gang
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.vaskerom_bod_lys_switch
  - service: switch.turn_off
    entity_id: switch.vaskerom_bod_lys_switch_2
    
    
    
    
# Magnet Lights Laundry-room
# Turn on ceiling lights when motion in laundry-room
- alias: 'Dør Vaskerom Lys Vaskerom På'
  trigger:
    entity_id: switch.magnet_dr_vaskerom
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.vaskerom_bod_lys_switch
  - service: switch.turn_on
    entity_id: switch.vaskerom_bod_lys_switch_2
    
    
# Magnet Lights hallway
# Turn on hallway lamp when front door opens
- alias: 'Magnet hallway light on'
  trigger:
    entity_id: switch.magnet_ytterdr
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.gang_lyst_kommode_switch
    
    
# Outdoor light
- alias: 'Outdoor light on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: light.turn_on
    entity_id: light.utelys
    
- alias: 'Outdoor light off'
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:45:00"
  action:
    service: light.turn_off
    entity_id: light.utelys