# Steam online notification
- alias: 'Steam Hilde Online'
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198105070411
    to: 'Online'
  action:
  - service: notify.notify
    data:
        message: "Hilde er online på steam"
        title: "Steam"