# Steam online notification
- alias: 'Steam Hilde Online'
  trigger:
  - platform: state
    entity_id: sensor.steam_76561198105070411
    to: 'online'
  condition:
    condition: state
    entity_id: input_boolean.automation_steam_notifications
    state: 'on'
  action:
  - service: notify.ios_veronica
    data:
        message: "Hamster-Hilde er online på steam"
        title: "Steam"