- alias: 'Vaskemaskin start'
  trigger:
    platform: state
    entity_id: sensor.washer_pwrdn
    to: 'True'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washmachine_status
  - service: notify.notify
    data:
      message: "Startet"
      title: "Vaskemaskin"
  - service: logbook.log
    data_template:
      name: Vaskemaskin
      message: Vaskemaskin startet

- alias: 'Vaskemaskin done'
  trigger:
    platform: state
    entity_id: sensor.washer_pwrdn
    to: 'False'
    for:
      minutes: 4
  condition:
    condition: state
    entity_id: input_boolean.washmachine_status
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: "Ferdig"
      title: "Vaskemaskin"
  - service: input_boolean.turn_off
    entity_id: input_boolean.washmachine_status
  - service: logbook.log
    data_template:
      name: Vaskemaskin
      message: Vaskemaskin ferdig